[package]
name = "comcart"
version = "0.1.0"
authors = ["Tommy Groshong <tgroshong@instructure.com>"]

[lib]
name = "comcart"
path = "src/lib.rs"

[dependencies]
lazy_static = "0.2.0"
regex = "0.1"
xml-rs = "0.3.0"
zip = "0.1.16"
